version: 2

models:
  - name: int_sessions_events_agg
    description: >
      Intermediate model to have events aggregate by user and sessions.
    columns:
      - name: session_id
        description: >
          .
        tests:
          - not_null
      - name: created_at_utc
        description: >
          .
        tests:
          - not_null
      - name: user_id
        description: >
          .
        tests:
          - not_null
      - name: page_view
        description: >
          .
        tests:
          - not_null
          - positive_values
      - name: add_to_cart
        description: >
          .
        tests:
          - not_null
          - positive_values
      - name: checkout
        description: >
          .
        tests:
          - not_null
          - positive_values
      - name: package_shipped
        description: >
          .
        tests:
          - not_null
          - positive_values 